// This file is auto-generated by scripts/sync-app-meta.mjs
// Do not edit manually.
export const APP_META = Object.freeze({
  "appName": "ILA Companion",
  "version": "1.0.0",
  "build": "production",
  "mode": "production",
  "buildId": "production-20260324041254-3c2636f-dirty",
  "commit": "3c2636f",
  "branch": "main",
  "dirty": true,
  "builtAt": "2026-03-24T04:12:54.919Z"
});

export default APP_META;
