// This file is auto-generated by scripts/sync-app-meta.mjs
// Do not edit manually.
export const APP_META = Object.freeze({
  "appName": "ILA Companion",
  "version": "1.0.0",
  "build": "production",
  "mode": "production",
  "buildId": "production-20260320090810-4670918-dirty",
  "commit": "4670918",
  "branch": "main",
  "dirty": true,
  "builtAt": "2026-03-20T09:08:10.664Z"
});

export default APP_META;
