// This file is auto-generated by scripts/sync-app-meta.mjs
// Do not edit manually.
export const APP_META = Object.freeze({
  "appName": "ILA Companion",
  "version": "1.0.0",
  "build": "production",
  "mode": "production",
  "buildId": "production-20260321121456-bf6ad62-dirty",
  "commit": "bf6ad62",
  "branch": "main",
  "dirty": true,
  "builtAt": "2026-03-21T12:14:56.975Z"
});

export default APP_META;
